/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


typedef volatile unsigned int vuint32_t ;
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>


// RCC
#define APB2ENR_BASE 0x40021000
#define  APB2ENR  *(volatile uint32_t *)(APB2ENR_BASE + 0x18)
#define RCC_IOPAEN (1<<2)

//GPIO   (input )
#define GPIO_PB      0x40010C00
#define  GPIO_PB_CRH      *(volatile uint32_t *)(GPIO_PB  +0x04)
#define  GPIO_PB_CRL      *(volatile uint32_t *)(GPIO_PB +0x00)
#define  GPIO_PB_ODR      *(volatile uint32_t *)(GPIO_PB +0x0C)
#define  GPIO_PB_IDR      *(volatile uint32_t *)(GPIO_PB + 0x08)


//GPIOA (input)

#define GPIO_PA       0x40010800
#define  GPIO_PA_CRH      *(volatile uint32_t *)(GPIO_PA +0x04)
#define  GPIO_PA_CRL      *(volatile uint32_t *)(GPIO_PA +0x00)
#define  GPIO_PA_ODR      *(volatile uint32_t *)(GPIO_PA +0x0C)
#define  GPIO_PA_IDR      *(volatile uint32_t *)(GPIO_PA + 0x08)


void clock_init() {
	// Enable gpioa clock
	APB2ENR |= 1<<2;
	// Enable gpioa clock
	APB2ENR |= 1<<3;

	//APB2ENR |=(1<<0);
}
void gpio_int(){
	//CRL for PA1 and PB1
    GPIO_PA_CRH =0x0;
    GPIO_PA_ODR=0x0;
	GPIO_PA_CRL=0x0;

	GPIO_PB_CRL=0x0;
	//PA1 input highZ
	GPIO_PA_CRL &=~(0b11<<4);
	GPIO_PA_CRL |=(0b01<<6);
	//PB1 output push pull mode
	//CNF 00 : general purpose output push-pull
	GPIO_PB_CRL |= (0b01 << 4);
	//01 : output mode max speed 10 MHZ
	GPIO_PB_CRL &=~(0b11 << 6);

	//PA13 input highz
	 GPIO_PA_CRH &= ~(0b11 << 20);
	 GPIO_PA_CRH |= (0b01 << 22 );

	 //PB13 output push pull mode
	 GPIO_PB_CRH |= (0b01 << 20);
	 GPIO_PB_CRH &= ~(0b11 << 22);
}

int main(void)
{
    /* Loop forever */
	clock_init();
	gpio_int();
	//PA1 >> connected external
	while(1){
	if (((GPIO_PA_IDR & (1<<1)) >> 1) ==0 )
			{
		      GPIO_PB_ODR ^= 1<<1;
				while((GPIO_PA_IDR & (1<<1)) >> 1 ==0 );
			}
	//PA13 >> connected
	if (((GPIO_PA_IDR & (1<<13)) >> 13 )==1 )
				{
			      GPIO_PB_ODR ^= 1<<13;

				}
	//delay
	for (int i =0; i<=500; i++);
}}
