/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#define APB2ENR_BASE 0x40021000
#define GPIO_PA       0x40010800

#define  APB2ENR  *(volatile uint32_t *)(APB2ENR_BASE + 0x18)
#define  CRH      *(volatile uint32_t *)(GPIO_PA +0x04)
#define  ODR      *(volatile uint32_t *)(GPIO_PA +0x0C)


int main(void)
{
	APB2ENR|=1<<2;
	CRH &=0xff0fffff;
	CRH|=0x00200000;

	while(1){

		ODR|=1<<13;
		for(int i=0;i<500;i++);
		ODR&=~(1<<13);
		for(int i=0;i<500;i++);
	}
}
